name = "VTKFortran"
version = "2.0.3"
author = "Stefano Zaghi"
copyright = "Copyright © 2022, Stefano Zaghi"
license = "Multiple licenses"
description = "pure Fortran VTK (XML) API"
maintainer = "Stefano Zaghi"
homepage = "https://github.com/szaghi/VTKFortran"

[library]
source-dir = "src/lib"

[install]
library = true

[dependencies]
[dependencies.FoXy]
git = "https://github.com/Fortran-FOSS-Programmers/FoXy"
branch = "master"

[dependencies.PENF]
git = "https://github.com/szaghi/PENF"
branch = "master"

[dependencies.BeFoR64]
git = "https://github.com/szaghi/BeFoR64"
branch = "master"

[dependencies.StringiFor]
git = "https://github.com/szaghi/StringiFor"
branch = "master"
