is_allocated – Lib_VTK_IO
is_allocated Function
5 statements
Source File
private elemental function is_allocated(self)
Type Bound
string
Arguments
Type Intent Optional Attributes Name
class(string), intent(in) :: self
Return Value logical
Called by
Source Code
   elemental function is_allocated(self)
   !< Return true if the string is allocated.
   !<
   !<```fortran
   !< type(string) :: astring
   !< logical      :: test_passed(2)
   !< test_passed(1) = astring%is_allocated().eqv..false.
   !< astring = 'hello'
   !< test_passed(2) = astring%is_allocated().eqv..true.
   !< print '(L1)', all(test_passed)
   !<```
   !=> T <<<
   class(string), intent(in) :: self     !< The string.
   logical                   :: is_allocated !< Result of the test.
   is_allocated = allocated(self%raw)
   endfunction is_allocated
Call graph
assign_tag calls is_allocated
get_content calls is_allocated, search
is_parsed calls is_allocated
parse calls is_allocated
search calls is_allocated, parse
stringify calls is_allocated, stringify, stringify_recursive
volatile_doctest calls is_allocated
content calls get_content
create_tag_nested calls stringify
stringify_recursive calls stringify, stringify_recursive
write_end_tag calls stringify
write_self_closing_tag calls stringify
write_start_tag calls stringify
write_tag calls stringify
foxy_test_add_attributes calls stringify
foxy_test_create_tag calls parse, stringify
foxy_test_delete_attributes calls stringify
foxy_test_delete_content calls stringify
foxy_test_indent_tag calls stringify
xml_tag calls create_tag_nested
finalize calls write_end_tag, write_dataarray_appended, parse_scratch_files
write_connectivity calls write_end_tag, write_start_tag, write_dataarray
write_dataarray_appended calls write_end_tag, write_start_tag
write_dataarray_location_tag calls write_end_tag, write_start_tag
write_dataarray_tag calls write_tag
write_dataarray_tag_appended calls write_self_closing_tag
write_fielddata_tag calls write_end_tag, write_start_tag
write_geo_rect_data3_rank1_r4p calls write_end_tag, write_start_tag, write_dataarray
write_geo_rect_data3_rank1_r8p calls write_end_tag, write_start_tag, write_dataarray
write_geo_strg_data1_rank2_r4p calls write_end_tag, write_start_tag, write_dataarray
write_geo_strg_data1_rank2_r8p calls write_end_tag, write_start_tag, write_dataarray
write_geo_strg_data1_rank4_r4p calls write_end_tag, write_start_tag, write_dataarray
write_geo_strg_data1_rank4_r8p calls write_end_tag, write_start_tag, write_dataarray
write_geo_strg_data3_rank1_r4p calls write_end_tag, write_start_tag, write_dataarray
write_geo_strg_data3_rank1_r8p calls write_end_tag, write_start_tag, write_dataarray
write_geo_strg_data3_rank3_r4p calls write_end_tag, write_start_tag, write_dataarray
write_geo_strg_data3_rank3_r8p calls write_end_tag, write_start_tag, write_dataarray
write_geo_unst_data1_rank2_r4p calls write_end_tag, write_start_tag, write_dataarray
write_geo_unst_data1_rank2_r8p calls write_end_tag, write_start_tag, write_dataarray
write_geo_unst_data3_rank1_r4p calls write_end_tag, write_start_tag, write_dataarray
write_geo_unst_data3_rank1_r8p calls write_end_tag, write_start_tag, write_dataarray
write_parallel_block_file calls write_self_closing_tag
write_parallel_block_files_array calls write_self_closing_tag
write_parallel_block_files_string calls write_self_closing_tag
write_parallel_close_block calls write_end_tag
write_parallel_dataarray calls write_self_closing_tag
write_parallel_geo calls write_self_closing_tag
write_parallel_open_block calls write_start_tag
write_piece_end_tag calls write_end_tag
write_piece_start_tag calls write_start_tag
write_piece_start_tag_unst calls write_start_tag
write_topology_tag calls write_end_tag, write_self_closing_tag, write_start_tag
foxy_test_add_tag calls stringify
foxy_test_delete_tag calls stringify
foxy_test_parse_file_simple calls stringify
foxy_test_parse_string_nested_tags calls stringify
foxy_test_parse_string_simple calls stringify
foxy_test_write_tag calls stringify
initialize calls write_topology_tag, finalize
write_block_array calls write_parallel_close_block, write_parallel_open_block, write_parallel_block_files
write_block_string calls write_parallel_close_block, write_parallel_open_block, write_parallel_block_files
write_dataarray1_rank1_i1p calls write_dataarray_tag, write_dataarray_tag_appended
write_dataarray1_rank1_i2p calls write_dataarray_tag, write_dataarray_tag_appended
write_dataarray1_rank1_i4p calls write_dataarray_tag, write_dataarray_tag_appended
write_dataarray1_rank1_i8p calls write_dataarray_tag, write_dataarray_tag_appended
write_dataarray1_rank1_r4p calls write_dataarray_tag, write_dataarray_tag_appended
write_dataarray1_rank1_r8p calls write_dataarray_tag, write_dataarray_tag_appended
write_dataarray1_rank2_i1p calls write_dataarray_tag, write_dataarray_tag_appended
write_dataarray1_rank2_i2p calls write_dataarray_tag, write_dataarray_tag_appended
write_dataarray1_rank2_i4p calls write_dataarray_tag, write_dataarray_tag_appended
write_dataarray1_rank2_i8p calls write_dataarray_tag, write_dataarray_tag_appended
write_dataarray1_rank2_r4p calls write_dataarray_tag, write_dataarray_tag_appended
write_dataarray1_rank2_r8p calls write_dataarray_tag, write_dataarray_tag_appended
write_dataarray1_rank3_i1p calls write_dataarray_tag, write_dataarray_tag_appended
write_dataarray1_rank3_i2p calls write_dataarray_tag, write_dataarray_tag_appended
write_dataarray1_rank3_i4p calls write_dataarray_tag, write_dataarray_tag_appended
write_dataarray1_rank3_i8p calls write_dataarray_tag, write_dataarray_tag_appended
write_dataarray1_rank3_r4p calls write_dataarray_tag, write_dataarray_tag_appended
write_dataarray1_rank3_r8p calls write_dataarray_tag, write_dataarray_tag_appended
write_dataarray1_rank4_i1p calls write_dataarray_tag, write_dataarray_tag_appended
write_dataarray1_rank4_i2p calls write_dataarray_tag, write_dataarray_tag_appended
write_dataarray1_rank4_i4p calls write_dataarray_tag, write_dataarray_tag_appended
write_dataarray1_rank4_i8p calls write_dataarray_tag, write_dataarray_tag_appended
write_dataarray1_rank4_r4p calls write_dataarray_tag, write_dataarray_tag_appended
write_dataarray1_rank4_r8p calls write_dataarray_tag, write_dataarray_tag_appended
write_dataarray3_rank1_i1p calls write_dataarray_tag, write_dataarray_tag_appended
write_dataarray3_rank1_i2p calls write_dataarray_tag, write_dataarray_tag_appended
write_dataarray3_rank1_i4p calls write_dataarray_tag, write_dataarray_tag_appended
write_dataarray3_rank1_i8p calls write_dataarray_tag, write_dataarray_tag_appended
write_dataarray3_rank1_r4p calls write_dataarray_tag, write_dataarray_tag_appended
write_dataarray3_rank1_r8p calls write_dataarray_tag, write_dataarray_tag_appended
write_dataarray3_rank3_i1p calls write_dataarray_tag, write_dataarray_tag_appended
write_dataarray3_rank3_i2p calls write_dataarray_tag, write_dataarray_tag_appended
write_dataarray3_rank3_i4p calls write_dataarray_tag, write_dataarray_tag_appended
write_dataarray3_rank3_i8p calls write_dataarray_tag, write_dataarray_tag_appended
write_dataarray3_rank3_r4p calls write_dataarray_tag, write_dataarray_tag_appended
write_dataarray3_rank3_r8p calls write_dataarray_tag, write_dataarray_tag_appended
write_dataarray6_rank1_i1p calls write_dataarray_tag, write_dataarray_tag_appended
write_dataarray6_rank1_i2p calls write_dataarray_tag, write_dataarray_tag_appended
write_dataarray6_rank1_i4p calls write_dataarray_tag, write_dataarray_tag_appended
write_dataarray6_rank1_i8p calls write_dataarray_tag, write_dataarray_tag_appended
write_dataarray6_rank1_r4p calls write_dataarray_tag, write_dataarray_tag_appended
write_dataarray6_rank1_r8p calls write_dataarray_tag, write_dataarray_tag_appended
write_dataarray6_rank3_i1p calls write_dataarray_tag, write_dataarray_tag_appended
write_dataarray6_rank3_i2p calls write_dataarray_tag, write_dataarray_tag_appended
write_dataarray6_rank3_i4p calls write_dataarray_tag, write_dataarray_tag_appended
write_dataarray6_rank3_i8p calls write_dataarray_tag, write_dataarray_tag_appended
write_dataarray6_rank3_r4p calls write_dataarray_tag, write_dataarray_tag_appended
write_dataarray6_rank3_r8p calls write_dataarray_tag, write_dataarray_tag_appended
write_data calls write_connectivity, write_dataarray, write_geo, write_piece
write_pvts calls write_parallel_dataarray, write_parallel_geo, write_dataarray
parse_scratch_files calls write_parallel_block_files, write_block
write_check calls write_dataarray, write_fielddata, write_geo, write_piece
write_fielddata1_rank0 calls write_dataarray
write_slave calls write_dataarray, write_fielddata, write_geo, write_piece
write_vts calls write_dataarray, write_geo, write_piece
vtk_fortran_write_pvts calls write_pvts, write_vts
vtk_fortran_write_vtr calls write_dataarray, write_fielddata, write_geo, write_piece
vtk_fortran_write_vtu calls write_data
vtk_fortran_write_volatile calls write_check, write_slave
vtk_fortran_write_vtm calls write_block, write_data
vtk_fortran_write_vts calls write_data