upper – Lib_VTK_IO
upper Function
13 statements
Source File
private elemental function upper(self)
Type Bound
string
Arguments
Type Intent Optional Attributes Name
class(string), intent(in) :: self
Return Value type(string)
Called by
Source Code
   elemental function upper(self)
   !< Return a string with all uppercase characters.
   !<
   !<```fortran
   !< type(string) :: astring
   !< logical      :: test_passed(1)
   !< astring = 'Hello WorLD!'
   !< test_passed(1) = astring%upper()//''=='HELLO WORLD!'
   !< print '(L1)', all(test_passed)
   !<```
   !=> T <<<
   class(string), intent(in) :: self  !< The string.
   type(string)              :: upper !< Upper case string.
   integer                   :: n1    !< Characters counter.
   integer                   :: n2    !< Characters counter.
   if (allocated(self%raw)) then
      upper = self
      do n1=1, len(self%raw)
         n2 = index(LOWER_ALPHABET, self%raw(n1:n1))
         if (n2>0) upper%raw(n1:n1) = UPPER_ALPHABET(n2:n2)
      enddo
   endif
   endfunction upper
Call graph
decode calls upper
encode calls upper
initialize calls upper, finalize
read_file calls upper, read_lines
read_line calls upper
read_lines calls upper, read_line
write_block_scratch calls upper
write_block_string calls upper
write_dataarray_location_tag calls upper
write_fielddata_tag calls upper
write_file calls upper, write_lines
write_line calls upper
write_tag calls upper
volatile_doctest calls upper, encode, read_file, write_file, read_line, decode, read_lines, glob
glob_string calls read_file
write_check calls initialize, write_dataarray, write_fielddata, write_geo
write_lines calls write_line
write_slave calls initialize, write_dataarray, write_fielddata, write_geo
write_vts calls initialize, write_dataarray, write_geo
stringifor_test_csv_naive_parser calls read_file, write_file
stringifor_test_parse_large_csv calls read_file
vtk_fortran_write_vtm calls initialize, write_block, write_data
vtk_fortran_write_vtr calls initialize, write_dataarray, write_fielddata, write_geo
vtk_fortran_write_vts calls initialize, write_data
vtk_fortran_write_vtu calls initialize, write_data
glob calls glob_string, glob_character
parse_scratch_files calls write_block
write_connectivity calls write_dataarray
write_data calls write_dataarray, write_geo, write_connectivity
write_fielddata1_rank0 calls write_dataarray
write_geo_rect_data3_rank1_r4p calls write_dataarray
write_geo_rect_data3_rank1_r8p calls write_dataarray
write_geo_strg_data1_rank2_r4p calls write_dataarray
write_geo_strg_data1_rank2_r8p calls write_dataarray
write_geo_strg_data1_rank4_r4p calls write_dataarray
write_geo_strg_data1_rank4_r8p calls write_dataarray
write_geo_strg_data3_rank1_r4p calls write_dataarray
write_geo_strg_data3_rank1_r8p calls write_dataarray
write_geo_strg_data3_rank3_r4p calls write_dataarray
write_geo_strg_data3_rank3_r8p calls write_dataarray
write_geo_unst_data1_rank2_r4p calls write_dataarray
write_geo_unst_data1_rank2_r8p calls write_dataarray
write_geo_unst_data3_rank1_r4p calls write_dataarray
write_geo_unst_data3_rank1_r8p calls write_dataarray
write_pvts calls write_dataarray
vtk_fortran_write_pvts calls write_vts, write_pvts
vtk_fortran_write_volatile calls write_check, write_slave
finalize calls parse_scratch_files
glob_character calls glob