chars – Lib_VTK_IO
chars Function
9 statements
Source File
private pure function chars(self) result(raw)
Type Bound
string
Arguments
Type Intent Optional Attributes Name
class(string), intent(in) :: self
Return Value character(kind=CK, len=:), allocatable
Called by
Source Code
   pure function chars(self) result(raw)
   !< Return the raw characters data.
   !<
   !<```fortran
   !< type(string) :: astring
   !< astring = 'say all Hello WorLD!'
   !< print '(L1)', astring%chars()=='say all Hello WorLD!'
   !<```
   !=> T <<<
   class(string), intent(in)              :: self !< The string.
   character(kind=CK, len=:), allocatable :: raw  !< Raw characters data.
   if (allocated(self%raw)) then
     raw = self%raw
   else
     raw = ''
   endif
   endfunction chars
Call graph
colorize_str calls chars
finalize calls chars, write_end_tag, write_dataarray_appended, parse_scratch_files
get_content calls chars
glob_character calls chars, glob
initialize calls chars, write_topology_tag, finalize
name calls chars
read_file calls chars, read_lines
read_line calls chars
read_lines calls chars, read_line
stringify calls chars, stringify, stringify_recursive
write_block_scratch calls chars
write_block_string calls chars, write_parallel_open_block, write_parallel_block_files, write_parallel_close_block
write_dataarray_appended calls chars, write_end_tag, write_start_tag
write_dataarray_location_tag calls chars, write_end_tag, write_start_tag
write_dataarray_tag calls chars, write_tag
write_dataarray_tag_appended calls chars, write_self_closing_tag
write_fielddata_tag calls chars, write_end_tag, write_start_tag
write_file calls chars, write_lines
write_line calls chars
write_parallel_block_files_string calls chars, write_self_closing_tag
write_parallel_dataarray calls chars, write_self_closing_tag
write_parallel_geo calls chars, write_self_closing_tag
write_parallel_open_block calls chars, write_start_tag
write_piece_start_tag calls chars, write_start_tag
write_piece_start_tag_unst calls chars, write_start_tag
write_tag calls chars, stringify
write_topology_tag calls chars, write_end_tag, write_self_closing_tag, write_start_tag
volatile_doctest calls chars, read_line, read_lines, read_file, write_file, glob, colorize
glob calls glob_character, glob_string
content calls get_content
create_tag_nested calls stringify
delete_tag calls name
glob_string calls read_file
stringify_recursive calls stringify, stringify_recursive
write_block_array calls write_parallel_open_block, write_parallel_block_files, write_parallel_close_block
write_check calls initialize, write_dataarray, write_fielddata, write_piece, write_geo
write_dataarray1_rank1_i1p calls write_dataarray_tag, write_dataarray_tag_appended
write_dataarray1_rank1_i2p calls write_dataarray_tag, write_dataarray_tag_appended
write_dataarray1_rank1_i4p calls write_dataarray_tag, write_dataarray_tag_appended
write_dataarray1_rank1_i8p calls write_dataarray_tag, write_dataarray_tag_appended
write_dataarray1_rank1_r4p calls write_dataarray_tag, write_dataarray_tag_appended
write_dataarray1_rank1_r8p calls write_dataarray_tag, write_dataarray_tag_appended
write_dataarray1_rank2_i1p calls write_dataarray_tag, write_dataarray_tag_appended
write_dataarray1_rank2_i2p calls write_dataarray_tag, write_dataarray_tag_appended
write_dataarray1_rank2_i4p calls write_dataarray_tag, write_dataarray_tag_appended
write_dataarray1_rank2_i8p calls write_dataarray_tag, write_dataarray_tag_appended
write_dataarray1_rank2_r4p calls write_dataarray_tag, write_dataarray_tag_appended
write_dataarray1_rank2_r8p calls write_dataarray_tag, write_dataarray_tag_appended
write_dataarray1_rank3_i1p calls write_dataarray_tag, write_dataarray_tag_appended
write_dataarray1_rank3_i2p calls write_dataarray_tag, write_dataarray_tag_appended
write_dataarray1_rank3_i4p calls write_dataarray_tag, write_dataarray_tag_appended
write_dataarray1_rank3_i8p calls write_dataarray_tag, write_dataarray_tag_appended
write_dataarray1_rank3_r4p calls write_dataarray_tag, write_dataarray_tag_appended
write_dataarray1_rank3_r8p calls write_dataarray_tag, write_dataarray_tag_appended
write_dataarray1_rank4_i1p calls write_dataarray_tag, write_dataarray_tag_appended
write_dataarray1_rank4_i2p calls write_dataarray_tag, write_dataarray_tag_appended
write_dataarray1_rank4_i4p calls write_dataarray_tag, write_dataarray_tag_appended
write_dataarray1_rank4_i8p calls write_dataarray_tag, write_dataarray_tag_appended
write_dataarray1_rank4_r4p calls write_dataarray_tag, write_dataarray_tag_appended
write_dataarray1_rank4_r8p calls write_dataarray_tag, write_dataarray_tag_appended
write_dataarray3_rank1_i1p calls write_dataarray_tag, write_dataarray_tag_appended
write_dataarray3_rank1_i2p calls write_dataarray_tag, write_dataarray_tag_appended
write_dataarray3_rank1_i4p calls write_dataarray_tag, write_dataarray_tag_appended
write_dataarray3_rank1_i8p calls write_dataarray_tag, write_dataarray_tag_appended
write_dataarray3_rank1_r4p calls write_dataarray_tag, write_dataarray_tag_appended
write_dataarray3_rank1_r8p calls write_dataarray_tag, write_dataarray_tag_appended
write_dataarray3_rank3_i1p calls write_dataarray_tag, write_dataarray_tag_appended
write_dataarray3_rank3_i2p calls write_dataarray_tag, write_dataarray_tag_appended
write_dataarray3_rank3_i4p calls write_dataarray_tag, write_dataarray_tag_appended
write_dataarray3_rank3_i8p calls write_dataarray_tag, write_dataarray_tag_appended
write_dataarray3_rank3_r4p calls write_dataarray_tag, write_dataarray_tag_appended
write_dataarray3_rank3_r8p calls write_dataarray_tag, write_dataarray_tag_appended
write_dataarray6_rank1_i1p calls write_dataarray_tag, write_dataarray_tag_appended
write_dataarray6_rank1_i2p calls write_dataarray_tag, write_dataarray_tag_appended
write_dataarray6_rank1_i4p calls write_dataarray_tag, write_dataarray_tag_appended
write_dataarray6_rank1_i8p calls write_dataarray_tag, write_dataarray_tag_appended
write_dataarray6_rank1_r4p calls write_dataarray_tag, write_dataarray_tag_appended
write_dataarray6_rank1_r8p calls write_dataarray_tag, write_dataarray_tag_appended
write_dataarray6_rank3_i1p calls write_dataarray_tag, write_dataarray_tag_appended
write_dataarray6_rank3_i2p calls write_dataarray_tag, write_dataarray_tag_appended
write_dataarray6_rank3_i4p calls write_dataarray_tag, write_dataarray_tag_appended
write_dataarray6_rank3_i8p calls write_dataarray_tag, write_dataarray_tag_appended
write_dataarray6_rank3_r4p calls write_dataarray_tag, write_dataarray_tag_appended
write_dataarray6_rank3_r8p calls write_dataarray_tag, write_dataarray_tag_appended
write_end_tag calls stringify
write_lines calls write_line
write_pvts calls write_parallel_dataarray, write_parallel_geo, write_dataarray
write_self_closing_tag calls stringify
write_slave calls initialize, write_dataarray, write_fielddata, write_piece, write_geo
write_start_tag calls stringify
write_vts calls initialize, write_dataarray, write_piece, write_geo
foxy_test_add_attributes calls stringify
foxy_test_create_tag calls stringify
foxy_test_delete_attributes calls stringify
foxy_test_delete_content calls stringify
foxy_test_indent_tag calls stringify
stringifor_test_csv_naive_parser calls read_file, write_file
stringifor_test_parse_large_csv calls read_file
vtk_fortran_write_vtm calls initialize, write_block, write_data
vtk_fortran_write_vtr calls initialize, write_dataarray, write_fielddata, write_piece, write_geo
vtk_fortran_write_vts calls initialize, write_data
vtk_fortran_write_vtu calls initialize, write_data
xml_tag calls create_tag_nested
parse_scratch_files calls write_block, write_parallel_block_files
write_connectivity calls write_dataarray, write_end_tag, write_start_tag
write_data calls write_dataarray, write_piece, write_geo, write_connectivity
write_fielddata1_rank0 calls write_dataarray
write_geo_rect_data3_rank1_r4p calls write_dataarray, write_end_tag, write_start_tag
write_geo_rect_data3_rank1_r8p calls write_dataarray, write_end_tag, write_start_tag
write_geo_strg_data1_rank2_r4p calls write_dataarray, write_end_tag, write_start_tag
write_geo_strg_data1_rank2_r8p calls write_dataarray, write_end_tag, write_start_tag
write_geo_strg_data1_rank4_r4p calls write_dataarray, write_end_tag, write_start_tag
write_geo_strg_data1_rank4_r8p calls write_dataarray, write_end_tag, write_start_tag
write_geo_strg_data3_rank1_r4p calls write_dataarray, write_end_tag, write_start_tag
write_geo_strg_data3_rank1_r8p calls write_dataarray, write_end_tag, write_start_tag
write_geo_strg_data3_rank3_r4p calls write_dataarray, write_end_tag, write_start_tag
write_geo_strg_data3_rank3_r8p calls write_dataarray, write_end_tag, write_start_tag
write_geo_unst_data1_rank2_r4p calls write_dataarray, write_end_tag, write_start_tag
write_geo_unst_data1_rank2_r8p calls write_dataarray, write_end_tag, write_start_tag
write_geo_unst_data3_rank1_r4p calls write_dataarray, write_end_tag, write_start_tag
write_geo_unst_data3_rank1_r8p calls write_dataarray, write_end_tag, write_start_tag
write_parallel_block_file calls write_self_closing_tag
write_parallel_block_files_array calls write_self_closing_tag
write_parallel_close_block calls write_end_tag
write_piece_end_tag calls write_end_tag
foxy_test_add_tag calls stringify
foxy_test_delete_tag calls delete_tag, stringify
foxy_test_parse_file_simple calls stringify
foxy_test_parse_string_nested_tags calls stringify
foxy_test_parse_string_simple calls stringify
foxy_test_write_tag calls stringify
vtk_fortran_write_pvts calls write_pvts, write_vts
vtk_fortran_write_volatile calls write_check, write_slave