write_end_tag – Lib_VTK_IO
write_end_tag Subroutine
11 statements
Source File
private subroutine write_end_tag(self, name)
Type Bound
xml_writer_abstract
Arguments
Type Intent Optional Attributes Name
class(xml_writer_abstract), intent(inout) :: self
character(len=*), intent(in) :: name
Calls
Called by
Source Code
   subroutine write_end_tag(self, name)
   !< Write `</tag_name>` end tag.
   class(xml_writer_abstract), intent(inout) :: self !< Writer.
   character(*),               intent(in)    :: name !< Tag name.
   self%indent = self%indent - 2
   self%tag = xml_tag(name=name, indent=self%indent)
   if (.not.self%is_volatile) then
      call self%tag%write(unit=self%xml, iostat=self%error, is_indented=.true., end_record=end_rec, only_end=.true.)
   else
      self%xml_volatile = self%xml_volatile//self%tag%stringify(is_indented=.true., only_end=.true.)//end_rec
   endif
   endsubroutine write_end_tag
Call graph
write_end_tag calls stringify
stringify calls str, attributes, chars, end_tag, is_allocated, self_closing_tag, start_tag
str calls str_a_i1p, str_a_i2p, str_a_i4p, str_a_i8p, str_a_r4p, str_a_r8p, str_bol, str_i1p, str_i2p, str_i4p, str_i8p, str_r4p, str_r8p, strf_i1p, strf_i2p, strf_i4p, strf_i8p, strf_r4p, strf_r8p
self_closing_tag calls attributes
start_tag calls attributes
str_a_i1p calls str_i1p
str_a_i2p calls str_i2p
str_a_i4p calls str_i4p
str_a_i8p calls str_i8p
str_a_r4p calls str_r4p
str_a_r8p calls str_r8p
str_r4p calls compact_real_string
str_r8p calls compact_real_string
finalize calls write_end_tag, write_dataarray_appended, parse_scratch_files
write_connectivity calls write_end_tag, write_dataarray
write_dataarray_appended calls write_end_tag
write_dataarray_location_tag calls write_end_tag
write_fielddata_tag calls write_end_tag
write_geo_rect_data3_rank1_r4p calls write_end_tag, write_dataarray
write_geo_rect_data3_rank1_r8p calls write_end_tag, write_dataarray
write_geo_strg_data1_rank2_r4p calls write_end_tag, write_dataarray
write_geo_strg_data1_rank2_r8p calls write_end_tag, write_dataarray
write_geo_strg_data1_rank4_r4p calls write_end_tag, write_dataarray
write_geo_strg_data1_rank4_r8p calls write_end_tag, write_dataarray
write_geo_strg_data3_rank1_r4p calls write_end_tag, write_dataarray
write_geo_strg_data3_rank1_r8p calls write_end_tag, write_dataarray
write_geo_strg_data3_rank3_r4p calls write_end_tag, write_dataarray
write_geo_strg_data3_rank3_r8p calls write_end_tag, write_dataarray
write_geo_unst_data1_rank2_r4p calls write_end_tag, write_dataarray
write_geo_unst_data1_rank2_r8p calls write_end_tag, write_dataarray
write_geo_unst_data3_rank1_r4p calls write_end_tag, write_dataarray
write_geo_unst_data3_rank1_r8p calls write_end_tag, write_dataarray
write_parallel_close_block calls write_end_tag
write_piece_end_tag calls write_end_tag
write_topology_tag calls write_end_tag
initialize calls write_topology_tag, finalize
write_block_array calls write_parallel_close_block
write_block_string calls write_parallel_close_block
write_data calls write_connectivity, write_dataarray, write_geo, write_piece
write_check calls write_dataarray, write_fielddata, write_geo, write_piece
write_fielddata1_rank0 calls write_dataarray
write_pvts calls write_dataarray
write_slave calls write_dataarray, write_fielddata, write_geo, write_piece
write_vts calls write_dataarray, write_geo, write_piece
vtk_fortran_write_vtr calls write_dataarray, write_fielddata, write_geo, write_piece
vtk_fortran_write_vtu calls write_data
parse_scratch_files calls write_block
vtk_fortran_write_pvts calls write_pvts, write_vts
vtk_fortran_write_volatile calls write_check, write_slave
vtk_fortran_write_vtm calls write_block, write_data
vtk_fortran_write_vts calls write_data